data1 = np.random.rand(10)
data2 = np.random.rand(100)
data3 = np.random.rand(10000)
y = np.linspace(0,10,1000)
plt.subplot(2, 3, 1)
sns.histplot(invG(data1), stat='density')
plt.plot(y,g(y), 'r', color = 'red', linestyle='--', label = 'exp')
plt.subplot(2,3,2)
sns.histplot(invG(data2), stat='density')
plt.plot(y,g(y), 'r', color = 'red', linestyle='--', label = 'exp')
plt.subplot(2,3,3)
sns.histplot(invG(data2), stat='density')
plt.plot(y,g(y), 'r', color = 'red', linestyle='--', label = 'exp')
ax1.title.set_text('10 samples')
ax2.title.set_text('100 samples')
ax3.title.set_text('10000 samples')
plt.show()
